name: nextmind_mobile_v2
description: "Nova vers√£o do aplicativo mobile do projeto integrador NextMind."
publish_to: 'none'
version: 2.0.0

environment:
  sdk: ^3.9.2

dependencies:
  auto_injector: ^2.1.1
  dio: ^5.9.0
  fade_shimmer: ^2.4.0
  firebase_auth: ^6.0.2
  firebase_core: ^4.1.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_svg: ^2.2.1
  freezed_annotation: ^3.1.0
  google_fonts: ^6.3.1
  google_sign_in: ^7.2.0
  intl: ^0.20.2
  carousel_slider: any
  json_annotation: ^4.9.0
  logger: ^2.6.1
  lucid_validation: ^1.3.1
  result_command: ^2.1.0
  result_dart: ^2.1.1
  routefly: ^3.1.3
  rxdart: ^0.28.0
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.2
  package_info_plus: ^9.0.0
  file_picker: ^8.1.2
  image_picker: ^1.1.1
  open_file: ^3.3.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.11.1
  build_runner: ^2.8.0
  freezed: ^3.2.3

flutter_launcher_icons:
  android: true
  adaptive_icon_background: "assets/images/logo/logotipo_verde.png"
  image_path: "assets/images/logo/logotipo_verde.png"

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/images/
    - assets/images/logo/
    - assets/animations/
